[package]
name = "backend-warp"
version = "0.1.0"
authors = ["FabianLars"]
edition = "2018"

[profile.release]
lto=true
panic='abort'

[dependencies]
tokio = { version = "0.3", features = ["macros"] }
warp = "0.2"
reqwest = { version = "0.10", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
