name: Deploy backend

on:
    push:
        branches:
            - master
        paths:
            - 'backend/**'

defaults:
    run:
        working-directory: backend

env:
    DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/postgres'
    PGPASSWORD: postgres

jobs:
    backend:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:latest
                env:
                    POSTGRES_DB: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_USER: postgres
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - uses: actions/checkout@v2

            - name: Setup Rust
              uses: hecrj/setup-rust-action@v1

            - name: Set up rotations table
              run: psql -U postgres -h 127.0.0.1 -d postgres -f backend/sql/rotations.sql

            - name: Build
              run: cargo build --release

            - name: Move file
              run: mkdir target/release/dist/ && mv target/release/backend target/release/dist/backend

            - name: Publish
              uses: easingthemes/ssh-deploy@master
              with:
                  REMOTE_HOST: ${{ secrets.SERVER_IP }}
                  REMOTE_USER: ${{ secrets.USERNAME }}
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  SOURCE: 'backend/target/release/dist/'
                  TARGET: '~/wwwbackend'

            - name: File permissions
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: cd ~/wwwbackend && sudo ./rights.sh && sudo systemctl daemon-reload && sudo systemctl restart fabianlars.de-backend.service
