name: Deploy backend

on:
    push:
        branches:
            - master
#        paths:
#            - 'backend/**'

jobs:
    backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Rust
              uses: hecrj/setup-rust-action@v1

            - name: Build
              run: cargo build -p backend --release

            - name: Rename file
              run: mkdir target/release/dist/ && mv target/release/backend target/release/dist/wapi

            - name: Publish
              uses: easingthemes/ssh-deploy@master
              with:
                  REMOTE_HOST: ${{ secrets.SERVER_IP }}
                  REMOTE_USER: ${{ secrets.USERNAME }}
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  SOURCE: 'target/release/dist/'
                  TARGET: '~/wwwbackend'

            - name: File permissions
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: cd ~/wwwbackend && sudo ./rights.sh
