name: Deploy backend

on:
    push:
        branches:
            - master
#        paths:
#            - 'backend/**'

jobs:
    backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Rust
              uses: hecrj/setup-rust-action@v1

            - name: Build
              run: cargo build -p backend --release

            - name: Rename file
              run: mv target/release/backend target/release/wapi

            - name: Publish
              uses: SamKirkland/web-deploy@master
              with:
                  target-server: ${{ secrets.SERVER_IP }}
                  remote-user: ${{ secrets.USERNAME }}
                  remote-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  rsync-options: --exclude=nothing.lol
                  source-path: 'target/release/'
                  destination-path: '~/wwwbackend'

            - name: File permissions
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: cd ~/wwwbackend && sudo ./rights.sh
