name: Deploy frontend

on:
    push:
        branches:
            - main

jobs:
    frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '14'

            - name: Install yarn
              run: npm install -g yarn

            - name: Install and Build
              run: |
                  yarn
                  yarn run build

            - name: Publish
              uses: easingthemes/ssh-deploy@master
              with:
                  REMOTE_HOST: ${{ secrets.SERVER_IP }}
                  REMOTE_USER: ${{ secrets.USERNAME }}
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  SOURCE: 'frontend/out/'
                  TARGET: '~/wwwhtml'
