name: Test

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Cache pnpm modules
        uses: actions/cache@v3
        env:
          cache-name: cache-pnnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - uses: pnpm/action-setup@v2
        with:
          version: 7.x.x
          run_install: true

      #- name: Type check
      #  run: pnpm type-check

      - name: Build project
        run: pnpm build
