name: Test

on:
    push:
    pull_request:

jobs:
    yarn-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '14'

            - name: Install yarn
              run: npm install -g yarn

            - name: Install and Build
              run: |
                  yarn
                  yarn test
